# Common Wireshark display filters extracted from the CellStream cheat sheet
# and commonly used examples. This is a curated subset for quick insertion.

COMMON_FILTERS = {
    "Operators": [
        "==",
        "!=",
        ">",
        ">=",
        "<",
        "<=",
        "and",
        "or",
        "xor",
        "not",
        "contains",
        "matches",
    ],
    "Frame": [
        "frame.number",
        "frame.time",
        "frame.time_epoch",
        "frame.len",
        "frame.cap_len",
        "frame.time_delta",
        "frame.time_relative",
        "frame.marked",
    ],
    "Ethernet": [
        "eth.addr",
        "eth.src",
        "eth.dst",
        "eth.type",
        "eth.len",
        "eth.lg",
        "eth.multicast",
    ],
    "ARP": [
        "arp.opcode",
        "arp.src.proto_ipv4",
        "arp.dst.proto_ipv4",
        "arp.src.hw_mac",
        "arp.dst.hw_mac",
    ],
    "VLAN": [
        "vlan.id",
        "vlan.priority",
        "vlan.etype",
    ],
    "IP": [
        "ip.src",
        "ip.dst",
        "ip.addr",
        "ip.proto",
        "ip.len",
        "ip.ttl",
        "ip.flags.df",
        "ip.flags.mf",
        "ip.fragment",
        "ip.checksum_bad",
    ],
    "IPv6": [
        "ipv6.src",
        "ipv6.dst",
        "ipv6.addr",
        "ipv6.nxt",
        "ipv6.hlim",
        "ipv6.flow",
    ],
    "ICMP": [
        "icmp.type",
        "icmp.code",
        "icmp.checksum_bad",
    ],
    "ICMPv6": [
        "icmpv6.type",
        "icmpv6.code",
        "icmpv6.checksum_bad",
    ],
    "TCP": [
        "tcp.srcport",
        "tcp.dstport",
        "tcp.port",
        "tcp.flags.syn",
        "tcp.flags.ack",
        "tcp.flags.reset",
        "tcp.flags.fin",
        "tcp.analysis.retransmission",
        "tcp.analysis.out_of_order",
        "tcp.len",
        "tcp.time_delta",
        "tcp.analysis.bytes_in_flight",
        "tcp.window_size",
    ],
    "UDP": [
        "udp.srcport",
        "udp.dstport",
        "udp.port",
        "udp.length",
        "udp.checksum_bad",
    ],
    "HTTP": [
        "http.request",
        "http.response",
        "http.host",
        "http.user_agent",
        "http.request.method",
        "http.response.code",
        "http.time",
    ],
    "DNS": [
        "dns",
        "dns.qry.name",
        "dns.qry.type",
        "dns.flags.rcode",
    ],
    "BGP": [
        "bgp.type",
        "bgp.as_path",
        "bgp.community_value",
        "bgp.next.hop",
    ],
    "OSPF": [
        "ospf.msg.hello",
        "ospf.msg.lsupdate",
        "ospf.srcrouter",
    ],
}

# Handy examples
FILTER_EXAMPLES = [
    "tcp.port == 80",
    "tcp.port == 443",
    "tcp.flags.syn == 1 && tcp.flags.ack == 0",
    "ip.addr == 192.0.2.10",
    "ip.src == 10.0.0.1",
    "ip.dst == 10.0.0.1",
    "dns",
    "http && ip.addr == 192.0.2.10",
    "tcp.len > 0 && !(tcp.analysis.keep_alive == 1)",
    "tcp.analysis.retransmission",
    "udp.port == 53 || tcp.port == 53",
]
