name: CI

on:
  push:
  pull_request:

jobs:
  lint-typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy
          pip install -e .[gui,datetime]

      - name: Ruff (E,F only)
        run: ruff check --select E,F --ignore E501 .

      - name: Mypy
        run: mypy PCAPpuller.py pcappuller gui_pcappuller.py
